### ISSUE TITLE
cannot "pas docker:up" in debian

### ISSUE THREAD

**Issue by NurAlam** [reekoheek/pas-docker#2]
SyntaxError: Unexpected token {
    at Object.parse (native)
    at null.<anonymous> (/home/rhoecoder/.nvm/v0.10.29/lib/node_modules/pas-docker/tasks/build.js:37:33)
    at IncomingMessage.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (_stream_readable.js:748:14)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:776:12
    at process._tickCallback (node.js:419:13)

**Comment by reekoheek** [comment]
this error happens because of docker api produce invalid json. pas-docker should fix this data first before parsing. 

this issue fixed in 70c64bd6ad7da3d1b4bcd03fec96862a7cd37cfa
