### ISSUE TITLE
error on pas docker:up

### ISSUE THREAD

**Issue by muhammadnurudin** [reekoheek/pas-docker#9]
xinix@xinix:~/workspace/docker/sikopat$ pas docker:up
| [xinix-technology/sikopat] stopping containers
| [xinix-technology/sikopat] building images
| | fpm: building xinix-technology-sikopat/fpm:latest
| | nginx: building xinix-technology-sikopat/nginx:latest
{"stream":"Step 0 : FROM docker:5000/xinix-technology/debian\n"}
{"status":"Repository docker:5000/xinix-technology/debian already being pulled by another client. Waiting."}

SyntaxError: Unexpected token {
    at Object.parse (native)
    at null.<anonymous> (/usr/lib/node_modules/pas-docker/tasks/build.js:57:33)
    at IncomingMessage.emit (events.js:95:17)
    at IncomingMessage.<anonymous> (_stream_readable.js:748:14)
    at IncomingMessage.emit (events.js:92:17)
    at _stream_readable.js:776:12
    at process._tickCallback (node.js:419:13)

**Comment by reekoheek** [comment]
fixed with fallback by verbose output of plain json string
